version: '3'
services:
  mongodb:
    image: mongo
    volumes:
     - ./mongo/data:/data/db
  httpd:
    build:
      context: ./httpd
    ports:
     - "8443:8443"
    depends_on:
     - server
  microauth:
    build:
      context: ./microauth
    volumes:
      - ./microauth/authorizationServer.js:/server/authorizationServer.js
    ports:
      - "9001:9001"
    command: node ./authorizationServer.js
  server:
    build:
      context: ./server-dev
    volumes:
     - ./target/:/server/
    command: java -jar /server/fapi-test-suite.jar --fintechlabs.devmode=true --fintechlabs.startredir=true
    links:
     - mongodb:mongodb
     - microauth:microauth
    depends_on:
     - mongodb
    logging:
      # limit logs retained on host
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "5"
