apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "trackableappname" . }}
  labels:
    app: {{ template "appname" . }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "appname" . }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: BASE_URL
          value: {{ .Values.service.url | quote }}
        - name: MICROAUTH_HOST
          value: {{ template "appname" . }}-microauth
        - name: MONGODB_HOST
          value: {{ template "appname" . }}-mongodb
        - name: JAVA_EXTRA_ARGS
          value: {{ .Values.javaArgs | quote }}
        - name: OIDC_GOOGLE_CLIENTID
          valueFrom:
            secretKeyRef:
              name: oidc-google-credentials
              key: clientid
        - name: OIDC_GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: oidc-google-credentials
              key: secret
        ports:
        - name: "{{ .Values.service.name }}"
          containerPort: {{ .Values.service.internalPort }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 15
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.internalPort }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
{{ toYaml .Values.resources | indent 12 }}
