{{- if .Values.service.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    httpd-server-snippet: |
      RequestHeader set X-Ssl-Cipher "%{SSL_CIPHER}s"
      RequestHeader set X-Ssl-Protocol "%{SSL_PROTOCOL}s"
      <Location "/test-mtls/">
        <If "%{HTTPS} == 'on'">
          SSLVerifyClient optional_no_ca
          RequestHeader set X-Ssl-Cert "%{SSL_CLIENT_CERT}s"
          RequestHeader set X-Ssl-Verify "%{SSL_CLIENT_VERIFY}s"
        </If>
      </Location>
spec:
  tls:
  - hosts:
    - {{ template "hostname" .Values.service.url }}
    secretName: {{ template "fullname" . }}-tls
  rules:
  - host: {{ template "hostname" .Values.service.url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
