replicaCount: 1
image:
  repository: gitlab.example.com/group/project
  tag: stable
  pullPolicy: Always
application:
  track: stable
  tier: web
service:
  name: microauth
  type: ClusterIP
  externalPort: 9001
  internalPort: 9001
resources: {}
